cards/urls.py
from django.contrib import admin
from django.urls import path
from jackets.views import jeckets, jacket_detail
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', jeckets),
    path('detail/<int:jacket_id>/', jacket_detail, name= 'detail')
]

jackets/models.py
from django.db import models

# Create your models here.

class Jacket(models.Model):
    brand = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.brand



class Jacket_Detail(models.Model):
    color = models.CharField(max_length=100)
    priceS = models.DecimalField(max_digits=5, decimal_places=2)
    priceM = models.DecimalField(max_digits=5, decimal_places=2)
    priceL = models.DecimalField(max_digits=5, decimal_places=2)
    priceXL = models.DecimalField(max_digits=5, decimal_places=2)
    picture = models.URLField(blank=False, null=False)
    jacktet = models.ForeignKey(Jacket, on_delete= models.CASCADE)

jackets/views.py
from django.shortcuts import render, get_object_or_404
from .models import Jacket, Jacket_Detail
# Create your views here.
def jeckets(request, *args, **kwargs):
    jackets = Jacket.objects.all()
    context = {'jeck': jackets}
    return render(request, 'jeckets/index.html', context=context)



def jacket_detail(request, jacket_id, *args, **kwargs):
    jacket = get_object_or_404(Jacket, id = jacket_id)
    context ={'jecks': jacket}
    return render(request, "jeckets/detail.html", context=context)

templates/jeckets/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product |Details </title>
    <style>
        h1, h2{
            margin-left:20px;
        }
        .class_1{
            display:flex;
        }
        .class_1_1, .class_1_2{
            margin:20px;
        }
       .class_1_1  img{
            width:350px;
        }
        .class_1_2  img{
            width:50px;
        }
        .active{
            border: 2px solid rgb(59, 16,107);
        }
        .hide{
            display:none;
        }
    
    </style>
</head>
<body>
    <h1>{{ jecks.brand }}</h1>
    <h2>{{ jecks.name }}</h2>
    <div class="class_1">
        <div class="class_1_1">
            <img src="{{ jecks.jacket_detail_set.first.picture }}" alt="" id= "picture">
        </div>
        <div class="class_1_2">
            {% for j in jecks.jacket_detail_set.all %}
                <div class="color">
                    <h3 {% if not forloop.first %} class="hide"{% endif %}>{{j.color}}</h3>
                </div>
                <div class="picture ">
                    <img src="{{j.picture}}" alt="" {% if forloop.first %} class="active"{% endif %} >
                </div>
                <br>
                <div class="price">
                    <select name="" id="" {% if not forloop.first %} class="hide"{% endif %}>
                        <option> Size</option>
                        <option value="{{j.priceS}}">S {{j.priceS}} $</option>
                        <option value="{{j.priceM}}">M {{j.priceM}} $</option>
                        <option value="{{j.priceL}}">L {{j.priceL}} $</option>
                        <option value="{{j.priceXL}}">XL {{j.priceXL}} $</option>
                        
                    </select>
                </div>
            {% endfor %}
        </div>
    </div>
    <script>
        picture = document.querySelector('#picture')
        pictures = document.querySelector('.class_1_2').getElementsByTagName('img')
        colors = document.querySelector('.class_1_2').getElementsByTagName('h3')
        prices = document.querySelector('.class_1_2').getElementsByTagName('select')
        choices = pictures.length
        IndexOfActivePicture = 0;
        for(let i=0; i < choices; i++ ){
            pictures[i].addEventListener('mouseover', function(){
                pictures[IndexOfActivePicture].classList.remove('active')
                pictures[i].classList.add('active')
                picture.src = pictures[i].src
                colors[IndexOfActivePicture].classList.add('hide')
                colors[i].classList.remove('hide')
                
                prices[IndexOfActivePicture].classList.add('hide')
                prices[i].classList.remove('hide')
                IndexOfActivePicture = i
            })
        }

    </script>
</body>
</html>

templates/jeckets/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jeckets | Products</title>
    <style>
        h1{
            text-align: center;

        }
        .jacket_detail img{
            width:300px;
        }
        .container{
            display:flex;
            
        }
        .jacket{
            width:25%;
            text-align:center;
            margin:10px;
        }

    
    
    </style>
</head>
<body>

<h1>This is Jecket Product</h1>
<div class="container">
    {% for j in jeck %}
        <div class="jacket">
            <h2> {{j.brand}} </h2>
            <h3> {{j.name}} </h3>
            <div class="jacket_detail">

                <a href="/detail/{{j.id}}">
                    <img src="{{ j.jacket_detail_set.first.picture }}" alt="">
                </a>
                <h4>{{ j.jacket_detail_set.first.priceS }} $</h4>
                
            </div>
        </div>
    {% endfor %}

</div>
    
</body>
</html>